version: '3.4'

services:
  rabbitchat.api:
    image: ${DOCKER_REGISTRY-}rabbitchatapi
    build:
      context: .
      dockerfile: src/RabbitChat.Api/Dockerfile
    environment:
      RABBITMQ__HOSTNAME: rabbitmq
      RABBITMQ__PORT: 5672
      RABBITMQ__USERNAME: mc
      RABBITMQ__PASSWORD: mc2
      RABBITMQ__VIRTUALHOST: main
      DBHOST: database
      DBPORT: 5432
      DBUSER: postgres
      DBPASSWORD: postgres
      DBDATABASE: rabbit_chat
    ports:
      - 8779:443
    networks: 
      - rabbitchat


  rabbitchat.consumersendmessage:
    image: ${DOCKER_REGISTRY-}rabbitchatconsumersendmessage
    build:
      context: .
      dockerfile: src/RabbitChat.ConsumerSendMessage/Dockerfile
    environment:
      RABBITMQ__HOSTNAME: rabbitmq
      RABBITMQ__PORT: 5672
      RABBITMQ__USERNAME: mc
      RABBITMQ__PASSWORD: mc2
      RABBITMQ__VIRTUALHOST: main
      DBHOST: database
      DBPORT: 5432
      DBUSER: postgres
      DBPASSWORD: postgres
      DBDATABASE: rabbit_chat
    networks: 
        - rabbitchat


  rabbitchat.consumerloadmessages:
    image: ${DOCKER_REGISTRY-}rabbitchatconsumerloadmessages
    build:
      context: .
      dockerfile: src/RabbitChat.ConsumerLoadMessages/Dockerfile
    environment:
      RABBITMQ__HOSTNAME: rabbitmq
      RABBITMQ__PORT: 5672
      RABBITMQ__USERNAME: mc
      RABBITMQ__PASSWORD: mc2
      RABBITMQ__VIRTUALHOST: main
      DBHOST: database
      DBPORT: 5432
      DBUSER: postgres
      DBPASSWORD: postgres
      DBDATABASE: rabbit_chat
    networks: 
        - rabbitchat

  rabbitmq:    
    build:
      context: ./rabbitmq
    ports:
    - "15672:15672"  #Management
    - "5672:5672"    #AMQP
    environment:
      RABBITMQ_DEFAULT_USER: mc
      RABBITMQ_DEFAULT_PASS: mc2
      RABBITMQ_DEFAULT_VHOST: main
    volumes:
      - mq_data:/var/lib/rabbitmq/mnesia
    networks: 
        - rabbitchat

  database:
    image: postgres:12
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=rabbit_chat
      - PGDATA:/tmp
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "55432:5432"
    networks:
      - rabbitchat

  redis:
    image: redis:6.2
    command: redis-server --requirepass Redis2021!
    ports:
      - 6379:6379
    networks:
      - rabbitchat



volumes:
  mq_data:
  pgdata:
    driver: local

networks:
  rabbitchat:



